version: '3.7'
services:
  portainer-agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    platform: linux/amd64
